### ISSUE TITLE
weird result

### ISSUE THREAD

**Issue by alChaCC** [mushishi78/box_packer#6] opened 2016-12-01 03:46 UTC
Hi @mushishi78 

Please check this case:
```
packings = BoxPacker.pack(
  container: { dimensions: [15, 20, 13], weight_limit: 50 },
  items: [
    { dimensions: [2, 3, 5], weight: 1 },
    { dimensions: [2, 3, 5], weight: 1 },
    { dimensions: [3, 3, 1], weight: 1 },
    { dimensions: [1, 1, 4], weight: 1 },
  ]
)
```
I expect the result should be
```
expect(packings.length).to eql(1)
expect(packings[0][:placements].length).to eql(4)
``` 
Right?

But the packing result I got is 
```
[
  { :placements=>
    [
      {:dimensions=>[5, 3, 2], :position=>[0, 0, 0], :weight=>1 },
      {:dimensions=>[5, 3, 2], :position=>[5, 0, 0], :weight=>1 }
    ],
  :weight=>2,
  :spaces=>
    [
      {:dimensions=>[5, 15, 10], :position=>[0, 3, 0]},
      {:dimensions=>[5, 3, 11], :position=>[0, 0, 2]},
      {:dimensions=>[20, 15, 3], :position=>[10, 0, 0]},
      {:dimensions=>[5, 15, 5], :position=>[5, 3, 0]},
      {:dimensions=>[5, 3, 6], :position=>[5, 0, 2]}
    ]
  }
]
```

**Comment by mushishi78** [comment] 2016-12-02 21:04
Thanks for the bug report. This is caused by `break` that should be a
`next`. I've pushed a fix to the published gem, but I won't be able to
push a fix to GitHub until after the weekend because I've left my
password at home.

**Closed** 2016-12-04 12:00 UTC
