### ISSUE TITLE
def place not consistant with def break_up_space

### ISSUE THREAD

**Issue by pocman** [mushishi78/box_packer#5] opened 2016-11-15 11:00 UTC
Hi, 
I have an issue with 2.0.0 l.28 in box_packer.rb
`place` returns an array of array of int but `break_up_space` expects a hash.
```
space = "{:dimensions=>[11, 11, 1], :position=>[10, 0, 0]}"
item = "{:dimensions=>[10, 6, 2], :weight=>50}"
# placement = place(item, space) returns "[[10, 6, 2], [10, 2, 6], [6, 10, 2], [6, 2, 10], [2, 10, 6], [2, 6, 10]]"
break_up_space(space, place(item, space))
```

**Comment by mushishi78** [comment] 2016-11-21 20:23
Hey man, thanks for the filling the issue. It's been a while since I wrote anything in Ruby and wasn't being weary enough of the implicit returns. It should be fixed now, hopefully.

You wouldn't be able to give me reproduction steps so that I add a test for it.

**Comment by pocman** [comment] 2016-11-21 22:09
Hi,
I don't have any example on hand but I must have try with the example from
the previous issue. ☺️

**Closed** 2016-12-04 12:01 UTC
